language: node_js

addons:
  sauce_connect: true # SAUCE_USERNAME & SAUCE_ACCESS_KEY env variables set in UI

  hosts:
    - web_tests.nr.jcx.ovh

node_js:
  # Supported Versions
  - "8.10" # Min version
  - "10"
  - "12"
  # Latest stable
  - "node"

# Run tests

install:
  - npm install
jobs:
  include:
    - stage: Sauce Labs
      node_js: 10
      script: npm run test:web:saucelabs
    - stage: Coverage
      node_js: 10
      script: npm run coverage:all
