language: node_js

node_js:
  # Supported Versions
  - "6"
  - "8"
  - "10"
  - "12"
  # Latest stable
  - "node"

# Run tests

install:
  - npm install
jobs:
  include:
    - stage: Coverage
      node_js: 10
      script: npm run coverage:all
