language: node_js

addons:
  hosts:
    - web_tests.nr.jcx.ovh # For saucelabs connect

node_js:
  # Supported Versions
  - "8.10" # Min version
  - "10"
  - "12"
  # Latest stable
  - "node"

# Run tests

install:
  - npm install
jobs:
  include:
    - stage: Sauce Labs
      node_js: 10
      script:
        - chmod +x .github/ci/install-sauceconnect.sh
        - npm run test:web:saucelabs
      after_success:
        - npm install --no-save @octokit/request@^5.4.2 @octokit/app@^4.2.0 backblaze-b2@1.5.0 promise-retry@1.1.1
        - node ./.github/ci/saucelabs_bot_travis.js

    - stage: Coverage
      node_js: 10
      script:
        - npm run coverage:all
        # ----- Mock Reporting Start -----
        - npm install --no-save @octokit/request@^5.4.2 @octokit/app@^4.2.0 # Install deps
        - npx nyc mocha --require @babel/register tests/mock.js --exit # Run only mocked tests
        - npx nyc report --reporter=text | node .github/ci/mock-reporter.js # Report the coverage % of mocked tests.
        # ----- Mock Reporting Stop
      env:
        - STAGE=COV

# Deploy on tags

deploy:
  provider: npm
  email: $NPME
  api_key: $NPMP
  edge: true # opt in to dpl v2
  on:
    # Only deploy on a tagged commit
    tags: true
    # Deploy on the coverage stage only
    condition: "$STAGE = COV"
    node_js: 10
