name: Documentation >> GitHub Pages

on:
  push:
    branches: 
      - master

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install
        run: |
          npm install
          npm run docs:build
      - name: Build and Deploy Repo
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'docs'
          #CNAME: (cname)
          CLEAN: true
